export const manualData = [
  {
    "title": "0. Introduction",
    "content": "**What is this app?**\nProductive Dashboard is a personal productivity web app that works on both desktop and mobile (installable as a PWA — Progressive Web App). It combines a focus timer, stopwatch, weekly timetable, task manager, roadmap planner, rich-text notes, health tracker, leaderboard, friends system, calendar with deadlines, countdown widgets, wallpaper system, and live quotes — all synced to the cloud so your data follows you everywhere.\n\n### Core Features\n- **Unified Workspace**: Eliminate distractions with a clean, centralized hub.\n- **Smart Timetable**: Take absolute control of your schedule with a precision interactive timetable.\n- **Task Management**: Never miss a deadline with intuitive drag-and-drop to-do lists.\n- **Global Leaderboard**: Turn productivity into a game and climb the global ranks.\n- **Focus Widgets**: Customize your space with sticky notes, weather updates, and goals.\n- **Cloud Sync**: Your data follows you seamlessly across all your devices in real-time.\n\n---"
  },
  {
    "title": "0. Installing the App on Your Device",
    "content": "This app is a **PWA (Progressive Web App)** — it installs like a native app directly from your browser. No app store needed.\n\n### On Mobile (Android — Chrome)\n1. Open the app URL in **Chrome**.\n2. Tap the **three-dot menu (⋮)** at the top-right corner of Chrome.\n3. Tap **\"Add to Home screen\"** or **\"Install app\"**.\n4. A prompt appears — tap **\"Install\"** or **\"Add\"**.\n5. The app icon appears on your home screen. Tap it to open the app in full-screen, just like a native app — no browser bar visible.\n\n### On Mobile (iOS — Safari)\n1. Open the app URL in **Safari** (must be Safari, not Chrome, on iPhone).\n2. Tap the **Share button** (box with arrow pointing up) at the bottom of the screen.\n3. Scroll down and tap **\"Add to Home Screen\"**.\n4. Tap **\"Add\"** in the top-right.\n5. The icon appears on your home screen.\n\n### On Desktop (Chrome / Edge)\n1. Open the app URL in **Chrome** or **Edge**.\n2. Look for the **install icon** (computer screen with a down-arrow) in the browser's address bar on the right side.\n3. Click it → click **\"Install\"** in the popup.\n4. The app opens in its own window (no browser tabs, no address bar) — feels like a desktop app.\n5. It also appears in your Start Menu / taskbar like any other installed app.\n\n> **Tip:** If you don't see the install icon in the address bar, try the three-dot menu (⋮) at the top-right → look for **\"Install Productive Dashboard\"** or **\"Cast, save, and share → Install page as app\"**.\n\n---"
  },
  {
    "title": "Using the App Offline & Sync Behaviour",
    "content": "The app is designed to keep working even when your internet connection drops.\n\n### What works without internet\n- The **Focus Timer** runs entirely on-device. It will not stop, pause, or lose time if you go offline.\n- **Tasks, Notes, Timetable, Roadmap, Countdowns** — you can view and edit all of them. Changes are saved locally in your browser instantly.\n- **Health logs, Stats** — readable and writable offline.\n\n### What requires internet\n- **Logging in / registering** — needs internet for the OTP and authentication.\n- **Leaderboard, Friends, Broadcasts** — these pull live data from the server.\n- **Cloud Sync (saving to cloud)** — write operations are queued and pushed when internet returns.\n\n### How sync works\nYour data is saved to your browser first (instant, always works), and then pushed to the cloud server in the background.\n\n- If you edit something while offline, it is stored locally.\n- When internet reconnects, the app automatically detects this and pushes the pending data to the cloud.\n- **You will not lose data** by going offline mid-session.\n\n> **Important:** Data lives in your browser's local storage AND the cloud. If you clear your browser data / use a different browser without logging in, your local copy is gone — but the cloud copy is safe. Logging in on any device restores your data from the cloud.\n\n---"
  },
  {
    "title": "1. First Launch — Login / Register Screen",
    "content": "When you open the app for the first time, you will land on the **Login screen**, not the dashboard. You must create an account or log in before anything else is accessible.\n\n### Registering a New Account\n1. Click **\"Need an account? Register\"** on the login screen.\n2. Fill in: **Email**, **Username**, **Password**.\n3. Submit — a **6-digit OTP** is sent to your email (check spam if not visible).\n4. Enter the OTP on the next screen to verify your email.\n\n> **If the app gets stuck on a \"Syncing...\" or loading screen after registration:**\n> This is a known first-load quirk. Simply **close the browser tab / app window completely and reopen it**. Then log in normally with your username and password. Your account is already created — do not register again.\n\n### Logging In\n- Enter your **Username or Email** + **Password** → Login.\n\n### Forgot Password\n1. Click \"Forgot Password?\" on the login screen.\n2. Enter your registered email → an OTP is sent.\n3. Enter the OTP + your new password → done. Then log in.\n\n---"
  },
  {
    "title": "2. The Dashboard Layout",
    "content": "After login, you see the main dashboard — a full-screen wallpaper with floating widgets.\n\n- **Bottom Dock** — quick-launch buttons for Timer, Tasks, Notes, Roadmap, Stats, Calendar, Timetable, etc.\n- **Right Toolbar** — Health, Stopwatch, Settings and other secondary toggle icons.\n- **Draggable Widgets** — Clock, Calendar, Timer, Countdowns. Drag them anywhere on the screen.\n- **Settings (⚙️)** — accessed via the dock or toolbar; contains all configuration panels.\n\nThe loading screen that appears on startup shows your profile picture and intro text while data is syncing. If syncing takes longer than expected, it automatically switches to **Motivator Mode** — showing a random motivational quote and a feature carousel to keep you engaged while the data loads.\n\n---"
  },
  {
    "title": "3. Account & Cloud Sync (Connect Tab)",
    "content": "Go to **Settings → Connect & News** after login.\n\nInside the Connect tab there are four sub-tabs: **Profile**, **Friends**, **News**, **Ranks**.\n\n### Profile Tab\n- Displays your username and a green **Sync Active** badge when cloud sync is working.\n- **Avatar:** Paste any public image URL (e.g. from imgur) → Save. The image updates everywhere including the loading screen.\n- **Alias:** Unlock with your password → set a nickname shown on the leaderboard instead of your real username.\n- **Sign Out** and **Delete Account** are both here. Delete requires unlocking first.\n\n> ⚠️ **90-Day Inactivity Warning:** Accounts with no logins for 90 days are **permanently deleted** along with all data. Export your backup regularly via **Settings → Data & Backup**.\n\n---"
  },
  {
    "title": "4. Focus Timer",
    "content": "The **Timer widget** sits on the main dashboard and is draggable.\n\n### Starting the Timer\n\n| Method | How |\n|---|---|\n| Quick preset | Click **5m**, **15m**, or **25m** button |\n| Custom minutes | Type a number in the \"Custom mins...\" box → press **Set** or Enter |\n| Click the display | When idle (showing `00:00`), click the big digits to open the editor and set hours:minutes manually |\n\n### Controls while running\n- **▶ / ⏸** — Start or Pause\n- **⏹** — Stop/Reset — saves any focus minutes already earned, then resets\n\n### What happens if you cancel in the middle?\nIf you press **⏹ Reset** mid-session, the app does **not lose your time**. Any minutes elapsed are saved to your focus history before the timer clears.\n\n> **Example:** Timer set to 45 min. You stop it at 20 min. Those 20 minutes are saved to today's focus log immediately.\n\n### Auto-save while running (internet loss protection)\nThe timer saves progress **every 10 minutes automatically** as you work — no internet required for the countdown itself. The saving happens in the background.\n\n- If you lose internet mid-session, the timer **keeps running locally** — it does not stop.\n- When internet returns, the next 10-minute checkpoint or the final save will sync to the cloud.\n- You will **never lose a completed or partially-done session** due to a connection drop.\n\n### Linking Timer to a Task\nFrom the **Tasks** panel, click the **▶** button next to any task. The timer starts and tracks focus time specifically for that task. The task name appears in a label above the timer display.\n\n### When the timer finishes\n- Alarm plays (if enabled in Settings → Sound).\n- A motivational quote popup appears.\n- All minutes for the session are recorded to your Stats.\n\n---"
  },
  {
    "title": "5. Stats (Focus History)",
    "content": "Open via the **📊 Stats** button on the dock/toolbar.\n\n**Left panel:**\n- **Today's Focus** — minutes logged today\n- **All Time** — total ever logged\n- **7-Day Avg / 30-Day Avg** — daily averages for recent periods\n- **Days Logged** — number of days you've used the timer\n\n**Right panel — Monthly Breakdown:**\n- Lists all months, sorted newest first.\n- Click any month row to expand it → shows individual day entries.\n- Each day entry also shows **Academic / Reading / Vocab** minutes if you logged Health data that day.\n\nYou can also click any **friend's 📊 Stats icon** in the Friends tab to view their breakdown in the same panel.\n\n---"
  },
  {
    "title": "6. Tasks",
    "content": "Open from the dock. A focused task list to plan your work session.\n\n- **Add a task:** Click the **+** button. Fill in title, optional due date, and time estimate.\n- **Start timer for a task:** Press **▶** next to any task — the Focus Timer starts and shows that task's name as context.\n- **Check off tasks:** Tap/click the checkbox on the left to mark as done.\n- **Delete a task:** Click the trash icon next to it.\n\nTasks with deadlines near the alert threshold trigger a **banner popup on the dashboard** (configure in Settings → Preferences → Deadline Alerts).\n\n---"
  },
  {
    "title": "7. Calendar & Deadlines",
    "content": "The **Mini Calendar** is a draggable widget on the dashboard. Open it from the dock if it is not visible.\n\n### Adding a Deadline to a Date\n1. Click any **date** on the calendar grid.\n2. The view switches to that day's deadline list.\n3. Click **\"+ ADD DEADLINE\"** at the bottom.\n4. Type the deadline name/note → press **Enter** or click away to save.\n5. To edit a saved deadline: **double-click** the text.\n6. To delete: click the 🗑️ trash icon next to it.\n\nDates with deadlines show a **red dot** on the calendar. If a deadline falls on today, the dot pulses.\n\n### View All Deadlines\nClick **\"VIEW ALL DEADLINES\"** at the bottom of the calendar widget to see a sorted list of every deadline across all dates.\n\n### Deadline Alert Notifications\nGo to **Settings → Preferences → Deadline Alerts**.\n\nSet the number of days in advance you want an alert popup. Example: set to **3** — if a deadline is in 3 days or less, a warning banner appears automatically on the dashboard each time you open the app.\n\n---"
  },
  {
    "title": "8. Timetable",
    "content": "A weekly schedule grid. Open from the dock or toolbar.\n\n### Basic use\n- **Weekdays / Weekends** — toggle using the `‹ ›` arrows on either side of the title.\n- Today's column is highlighted in purple automatically.\n- Click any cell → type the subject or activity (e.g. \"Maths\", \"Gym\") → press Tab or click away to save.\n- If you type the **exact same text** in back-to-back rows of the same day, those cells visually merge into one block automatically.\n\n### How the time column works\nThe time column on the left is **fully automatic** — you never type times manually. It works like this:\n\n1. You set a **Day Start Time** (e.g. 8:00 AM).\n2. Each row has a **duration** (e.g. 60 min).\n3. The app calculates every slot's start and end time by adding durations top-to-bottom from your start time.\n\n> **Example:** Start = 8:00 AM. Row 1 = 60 min → shows `8:00AM – 9:00AM`. Row 2 = 90 min → shows `9:00AM – 10:30AM`. Row 3 = 60 min → shows `10:30AM – 11:30AM`. You only needed to set durations; the times adjust automatically.\n\n**This means:** If you change any row's duration, all rows below it shift their times automatically.\n\n### Setting the Day Start Time\nClick the small **\"Day Starts: 9:00 AM\"** button just below the title. A time picker appears → choose your time → Save.\n\n- This is saved separately for **Weekdays** and **Weekends**.\n\n### Changing a slot's duration\nClick any **time cell** in the left column:\n- A small editor pops up on that cell.\n- Use **▲ +15** / **▼ -15** to adjust in 15-minute steps, or type a number directly (in minutes).\n- Press ✓ or Enter to confirm.\n- All subsequent row times update automatically.\n\n### Adding / Removing rows\nClick the **⚙️** settings icon next to the schedule title:\n\n| Option | What it does |\n|---|---|\n| Add Top Row | Adds a new slot before row 1 |\n| Add Bottom Row | Adds a new slot at the end |\n| Delete Top Row | Removes row 1 |\n| Delete Bottom Row | Removes the last row |\n| Reset Timetable | Resets to a default weekday + weekend schedule |\n\n---"
  },
  {
    "title": "9. Focus Mode & Panic Mode",
    "content": "### Desktop — Keyboard Shortcuts\nConfigure shortcuts in **Settings → Focus / Panic Mode**.\n\n| Mode | What it does |\n|---|---|\n| **Focus Mode** | Hides the widgets you selected in the \"Focus Specific Setup\" section. Press again to restore. |\n| **Panic Mode** | Instantly hides ALL widgets. Press again to restore. |\n\n- Click the shortcut input box → press your desired key combo (e.g. `Ctrl + H`) → it saves automatically.\n- You can also click **\"Trigger\"** button to test it manually.\n- **Switch Wallpaper on Panic** — toggle ON if you want the wallpaper to also change when Panic is triggered.\n\n### Mobile — Eye Icon Panic\nOn mobile, there is no keyboard. Instead:\n\n- Look for the **👁️ Eye icon** on the right side of the screen.\n- Tap it to trigger the Panic action instantly.\n\n**Panic Action has two modes** (set in Settings → Focus / Panic Mode → Panic Action):\n\n| Mode | What happens |\n|---|---|\n| **Redirect** | The browser immediately navigates to a random/neutral website, making the dashboard completely invisible to anyone looking. To return: press **Back** in the browser — the dashboard reloads and your session is still active. |\n| **Hide UI** | All widgets disappear and the screen goes transparent/blank. Tap the eye icon again to bring everything back. |\n\n---"
  },
  {
    "title": "10. Friends",
    "content": "**Settings → Connect & News → Friends tab** (requires login).\n\n### Adding a Friend\n1. Use the **search bar** to find users by username.\n2. Click **Send Request** next to their name.\n3. They will see a pending request badge on their Friends tab.\n\n### Accepting / Rejecting Requests\n- A red number badge on the Friends tab shows pending incoming requests.\n- Tap the request to **Accept ✓** or **Reject ✗**.\n\n### Viewing Friend Stats\n- In your friends list, click the **📊 Stats** icon next to a friend's name.\n- A panel opens showing their focus history — today's time, total time, and daily breakdown by month.\n- Click **\"My Stats\"** button to switch back to your own stats in the same view.\n\n### Friend Request Notifications\nWhen someone sends you a friend request, a **Friend Request popup notification** will appear automatically on your dashboard — so you never miss a request even if Settings is closed.\n\n### Removing a Friend\nClick the 🗑️ trash icon next to any friend → confirm.\n\n---"
  },
  {
    "title": "11. Leaderboard",
    "content": "**Settings → Connect & News → Ranks tab** (requires login).\n\n### How the Leaderboard Works\n- The leaderboard tracks your total accumulated focus time via the Timer.\n- It ranks all users by focus time for **Today / This Week / This Month** — toggle at the top.\n- Your own row is highlighted in the list.\n- Your **alias** is shown if you set one; otherwise your username is shown.\n- Use the search bar to find a specific user.\n- Click any user row to expand and see their stats breakdown.\n\n### Badges & Achievements\nAs you accumulate focused work hours, you can earn dynamic badges that appear next to your name on the leaderboard. Badges are awarded automatically to the top user who meets the strict minimum requirements:\n- **Daily Badge (🏆)**: Requires a minimum of **6 hours** of focus time in a single day.\n- **Weekly Badge (🌟)**: Requires a minimum of **42 hours** of focus time over the last 7 days.\n- **Monthly Badge (👑)**: Requires a minimum of **180 hours** of focus time over the last 30 days.\n\n*Note: Badges are incrementable! If you win the daily top spot with 6+ hours multiple times, your badge count will increase (e.g., \"🏆 2 Day\").*\n\n> Set your alias in **Settings → Connect → Profile → Security & Alias** (requires password unlock) to appear anonymously on the leaderboard.\n\n---"
  },
  {
    "title": "12. Roadmap Manager (Plans)",
    "content": "Open from the dock. A powerful, visual roadmap builder for long-term goals and projects.\n\n### Structure — Roadmaps and Topics\n- You can have **multiple roadmaps** (e.g. \"Semester Goals\", \"Career Path\", \"Personal Projects\"). Switch between them using the **roadmap name button** at the top of the view.\n- Each roadmap is a **tree of topics** — each topic can have subtopics nested up to 4 levels deep.\n- On **desktop**, topics alternate left and right along a central timeline. On **mobile**, topics stack in a left-aligned list.\n\n### Adding Topics\n1. Click **\"Add Main Topic\"** at the bottom of the roadmap view to add a root-level topic.\n2. Click the **⋮** menu on any existing topic → **➕ Subtopic** to add a nested child topic (up to 4 levels).\n3. A new topic is created with the name \"New Topic\" — click it to open the **Edit Topic** modal.\n\n### Editing a Topic\nClick any **leaf topic** (one with no children) directly, or click the **⋮ → Edit** on any topic. Inside the editor:\n- **Title** — the topic name.\n- **Description (Optional)** — additional notes below the title.\n- Click **Save** to confirm.\n\n### Topic Statuses\nEach topic has a status you can cycle through by clicking the **status button** (circle icon on the right of the topic card):\n\n| Icon | Status | Card Border Color |\n|---|---|---|\n| ⚪ | Pending | White/dim |\n| 🔵 | In Progress | Blue glow |\n| ✅ | Completed | Green |\n\nCompleted topics show the title with a strikethrough.\n\n### Filtering by Status\nUse the **legend bar** at the top (⚪ Pending / 🔵 In Progress / ✅ Completed) to filter the entire view to show only topics of that status across **all roadmaps** — this is called the **Synthetic View**. Click the active filter again to clear it.\n\n### Roadmap Deadline\nClick the **\"Set Deadline\"** badge at the top of the roadmap tree to set a target completion date. It shows how many days are left. In the Synthetic (filtered) view, you can also set per-status deadlines.\n\n### Managing Roadmaps\n- **Create a new roadmap:** Click the roadmap name at the top → **\"+ Create Roadmap\"** in the switcher popup.\n- **Switch roadmaps:** Click the roadmap name at the top → click any roadmap in the list.\n- **Delete a roadmap:** Scroll to the bottom of the roadmap view → click **\"Delete Entire Roadmap\"** (you must type DELETE to confirm).\n\n### Deleting a Topic\nClick **⋮** on any topic → **✕ Delete** → type \"DELETE\" to confirm. This also removes all of that topic's subtopics.\n\n---"
  },
  {
    "title": "13. Quick Notes",
    "content": "Open from the dock. A rich-text, multi-note writing space.\n\n### Managing Notes\n- **Create a note:** Click the **+** button in the top-right of the Notes sidebar.\n- **Switch notes:** Click any note title in the left sidebar (or top list on mobile).\n- **Rename a note:** Click the note title text at the top of the editor area and type to rename.\n- **Delete a note:** Click the 🗑️ trash icon next to any note in the sidebar (only visible when you have more than one note).\n\n### The Editor\n- Notes are **date-sectioned** — each day you write, a new date heading appears automatically. Your existing entries for previous days are preserved and visible below.\n- The editor supports full **rich text** formatting:\n\n| Button | Action |\n|---|---|\n| H1 | Large heading |\n| H2 | Medium heading |\n| P | Normal paragraph text |\n| **B** | Bold |\n| *I* | Italic |\n| U | Underline |\n| ☰ | Bullet list |\n| ↩ Undo / ↪ Redo | Undo or redo last change |\n\n- The **floating formatting toolbar** appears at the bottom of the editor — scroll it horizontally on small screens.\n- Notes **auto-save** 30 seconds after you stop typing, and immediately when you close the Notes modal.\n\n### Exporting Notes\n- **Export a single note:** Click the ⬇️ download icon next to any note in the sidebar — saves as a `.json` file.\n- **Export all notes:** Click the ⬇️ export icon in the top-right header of the Notes panel — exports all notes at once.\n\n---"
  },
  {
    "title": "14. Health Tracker",
    "content": "Open via the ❤️ icon on the right toolbar.\n\nLog daily metrics to track habits alongside your focus sessions:\n\n| Field | What to log |\n|---|---|\n| **Academic minutes** | Formal study / coursework time |\n| **Reading minutes** | Books, articles, research papers |\n| **Vocab words** | New words or concepts learned |\n\nThese appear in the **Monthly Breakdown in Stats** alongside your Focus Timer data — giving you a full picture of your learning day.\n\n---"
  },
  {
    "title": "15. Stopwatch",
    "content": "Separate from the Focus Timer. Records raw elapsed time for any activity.\n\n- **Start / Pause** — standard start and pause controls.\n- **Lap** — records the current time as a split point while continuing to count.\n- **Reset** — clears the current session.\n- Each completed session is saved with its timestamp and visible in your Stats history.\n\n> Use the Stopwatch for activities where you want to **measure time** without a countdown — e.g. reading sessions, workout durations, or any open-ended work blocks.\n\n---"
  },
  {
    "title": "16. Countdowns",
    "content": "A widget showing a list of upcoming target events with day countdowns.\n\n### Mobile Access\n- you can quickly access the Countdowns widget by **swiping left or right on the top pill/notch area** of the screen.\n\n### Features\n- **Add an event:** Click **+** in the Countdowns widget → enter the event name and target date.\n- The widget shows **\"X days left\"** for each event.\n- Events within your **Deadline Alert Days** threshold (set in Settings → Preferences) trigger a dashboard popup banner automatically.\n- If you have more than one countdown, a **chevron button (▲/▼)** at the bottom of the widget expands or collapses the full list.\n\n---"
  },
  {
    "title": "17. Wallpapers",
    "content": "**Settings → Wallpapers**\n\n### Choosing a Wallpaper\n- Pick from **built-in wallpapers** — a curated set of images and animated video backgrounds.\n- Click a wallpaper thumbnail to make it active immediately.\n\n### Custom Wallpapers via URL\n- Add up to **4 custom wallpapers for Desktop** and **4 for Mobile** by pasting an image URL.\n- The app stores separate wallpaper sets for desktop and mobile — so your phone gets an appropriately sized background.\n\n### Slideshow Mode\n- Toggle **Slideshow** on to have the wallpaper auto-cycle through your active wallpapers.\n- Set the **interval in minutes** — e.g. 30 minutes to switch wallpaper every half hour.\n\n### Locking & Hiding Wallpapers\n| Option | What it does |\n|---|---|\n| **Lock** | Slideshow skips this wallpaper — it stays as the permanent background until unlocked |\n| **Hide** | Removes the wallpaper from slideshow rotation without deleting it |\n\n---"
  },
  {
    "title": "18. Widget Settings & Preferences",
    "content": "**Settings → Preferences**\n\n### Widget Visibility\nToggle any widget on or off. Hidden widgets do not appear on the dashboard at all.\n\nAvailable toggles: Timer, Clock (with Today's Work), Calendar, Tasks, Notes, Timetable, Health, Stats, Plans (Roadmap), Stopwatch, Countdowns, Dock, Deadline Alerts, Settings Button.\n\n### Widget Drag Locking\n- When unlocked, all draggable widgets can be repositioned by dragging.\n- Toggle **lock** on any specific widget to prevent it from being moved accidentally. Other widgets remain draggable.\n- **Reset Default Positions** — resets ALL draggable widgets back to their original layout positions.\n\n### Right Toolbar Position\nAdjust the **vertical height offset** of the right-side toolbar (Health, Stopwatch, etc.). Use the slider to move it up or down to avoid overlapping other elements on your layout.\n\n### Display Options\n- **24-Hour Clock** — toggle between 12h AM/PM and 24h military format for the Big Clock.\n- **Deadline Alert Days** — how many days before a deadline the alert popup triggers on the dashboard.\n\n### Focus Mode — Specific Widget Setup\nIn the **Focus / Panic Mode** tab, you can individually select which widgets should be hidden when Focus Mode is triggered — so only your most important widgets remain visible during a focused work session.\n\n---"
  },
  {
    "title": "19. Sound Settings",
    "content": "**Settings → Sound Settings**\n\n| Setting | Description |\n|---|---|\n| **Enable Alarm Sound** | Plays audio when the Focus Timer ends |\n| **Enable Device Vibrate** | Vibrates your phone/tablet when the timer ends (mobile only) |\n| **Auto Stop Timer** | Slider from 5 seconds to 2 minutes — controls how long the alarm rings before stopping itself automatically |\n| **Select Alarm Sound** | Choose from a list of available ringtone options |\n\n---"
  },
  {
    "title": "20. Data & Backup",
    "content": "**Settings → Data & Backup**\n\n- **Export Data** — downloads a full `.json` backup of all your data (focus logs, tasks, notes, roadmap, health, etc.). Requires being logged in.\n- **Import Data** — upload a `.json` backup file.\n  - **Merge:** Combines the backup with your existing data (no data lost from either side).\n  - **Overwrite:** Replaces everything with the backup file.\n- **Clear Old Data** — delete focus history entries older than a chosen number of days.\n- **Clear All Data** — wipes all local data (irreversible).\n\n> **Tip:** Export your backup before clearing browser data or switching devices to avoid losing your local copy.\n\n---"
  },
  {
    "title": "21. Feedback & Bugs",
    "content": "**Settings → Feedback & Bugs**\n\nSubmit feedback directly to the developer from inside the app:\n\n- **💡 Feature request** — suggest a new feature you'd like to see.\n- **🐛 Bug report** — describe something that isn't working correctly.\n- **💬 General feedback** — any other comment or message.\n\nView your submission status:\n- *Reviewing* — received, not yet looked at\n- *Reviewed* — seen by developer\n- *✓ Roadmap!* — accepted and planned for a future update\n\n---"
  },
  {
    "title": "22. Hidden Widget Drag Controls ",
    "content": "many widgets can be controlled using swipe gestures instead of buttons for a faster experience:\n\n- **Countdowns**: Swipe left or right on the widget to switch between your countdowns. Swipe **UP** directly on the widget to close/hide it.  You can also do a right or left swipe on the top Focus Pill to toggle the Countdowns widget open or closed.\n- **Calendar**: Swipe left or right near top-left edge on screen to show or hide calendar quickly without calender button you can hide it from settings if you want.\n- **Task Manager**: Swipe left or right near top-right edge on screen to show or hide the tasks quickly without calender button you can hide it from settings if you want.\n- **Menus & Modals**: You can use mouse click and drag (or swipe on touch screens) to close or navigate the Settings side menu and the Health & Habits modal.\n- **Edge Panels**: The Health Rings (bottom-left) and Right Toolbar hide at the screen edges. Click or hover the exposed edge to expand them. Swipe right on the Toolbar to hide it, while the Health Rings will auto-hide after 8 seconds."
  },
  {
    "title": "Quick Reference",
    "content": "| What you want to do | Where |\n|---|---|\n| Start focus timer | Timer widget on dashboard |\n| See your focus logs | 📊 Stats button on dock |\n| Set weekly schedule | Timetable (dock) |\n| Add a deadline to a date | Click the date on the Calendar widget |\n| Set deadline alert threshold | Settings → Preferences → Deadline Alerts |\n| Plan long-term goals | Plans / Roadmap (dock) |\n| Add a roadmap topic | Roadmap → \"Add Main Topic\" button |\n| Filter roadmap by status | Click ⚪ / 🔵 / ✅ in the Roadmap legend bar |\n| Switch roadmaps | Click roadmap name at top of Roadmap view |\n| Write and format notes | Notes (dock) — use floating toolbar at bottom |\n| Export a single note | Notes sidebar → ⬇️ icon next to note title |\n| Export all notes | Notes → ⬇️ icon at top of sidebar |\n| Log health data (study/reading/vocab) | ❤️ icon on right toolbar |\n| Time an open-ended activity | Stopwatch (right toolbar) |\n| Add a countdown event | + button in Countdowns widget |\n| Check the leaderboard | Settings → Connect → Ranks tab |\n| Add / accept friends | Settings → Connect → Friends tab |\n| View a friend's stats | Friends tab → 📊 icon next to their name |\n| Backup your data | Settings → Data & Backup → Export |\n| Change wallpaper | Settings → Wallpapers |\n| Enable slideshow wallpapers | Settings → Wallpapers → Slideshow toggle |\n| Hide/show widgets | Settings → Preferences → Widget Visibility |\n| Lock widgets in place | Settings → Preferences → Widget Drag Locking |\n| Reset widget positions | Settings → Preferences → Reset Default Positions |\n| Panic button (mobile) | Tap 👁️ Eye icon on right side of screen to hide all and click on same place to get back all that icon becomes invisible on peak mode but remains on same place to toggle back |\n| Panic / Focus shortcut (desktop) | Settings → Focus / Panic Mode |\n| Set alias for leaderboard | Settings → Connect → Profile → Security & Alias |\n| Reset password | Login screen → \"Forgot Password?\" |\n| Submit a bug or feature request | Settings → Feedback & Bugs |\n| Delete your account | Settings → Connect → Profile → (unlock) → Delete Account |"
  }
];